"""Add timestamp fields to user

Revision ID: 3a25581bac99
Revises: 7adc8436a9ab
Create Date: 2023-12-25 00:47:20.585757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a25581bac99'
down_revision: Union[str, None] = '7adc8436a9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
