"""empty message

Revision ID: 83f91edfa3b8
Revises: 
Create Date: 2023-12-23 22:14:53.426620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83f91edfa3b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('full_name', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
                    sa.Column('username', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='users_pkey')
                    )
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=True)
    
    op.create_table('card_requests',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('request', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
                    sa.Column('language_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
                    sa.Column('generated_prompt', sa.VARCHAR(length=100000), autoincrement=False, nullable=False),
                    sa.Column('revised_prompt', sa.VARCHAR(length=100000), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], name='card_requests_user_fkey'),
                    sa.PrimaryKeyConstraint('id', name='card_requests_pkey')
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.drop_table('users')
    op.drop_table('card_requests')
