---
  name: Terraform Cloud Apply Run
  
  on:
    push:
      branches:
        - master

      paths:
        - 'terraform/**.tf'
  
  
  concurrency: production
  

  env:
    TF_CLOUD_ORGANIZATION: "nurikodd" ## Name of your existing Terraform Cloud Organization. RECOMMENDED: use repository variables. ex. "${{ vars.TF_CLOUD_ORGANIZATION }}"
    TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
    TF_WORKSPACE: "tele-bot"
    CONFIG_DIRECTORY: "./terraform/" ## Directory of your Terraform Configuration. Relative to the project root.
    TF_LOG: DEBUG ## Helpful for troubleshooting
    # TF_MAX_TIMEOUT: "30m" ## If you wish to override the default "1h"
  
  jobs:
    terraform-cloud-apply-run:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
  
        - uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.1.1
          id: upload
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            directory: ${{ env.CONFIG_DIRECTORY }}
  
        - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.1.1
          id: create-run
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
  
        - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.1.1
          id: apply
          if: ${{ fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable }}
          with:
            run: ${{ steps.create-run.outputs.run_id }}
            comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"